### ISSUE TITLE
TSC Alpha-3RB

### ISSUE THREAD

**Issue by dontuse** [januslo/react-native-bluetooth-escpos-printer#45]
Hi, thx for the lib.
I have printer [Alpha-3RB](https://www.tscprinters.com/EN/Product/Series/Mobile%20Barcode%20Printers/Alpha-3R) , blue-tooth connection trigger EVENT_CONNECTION_LOST, after connect.

**Comment by dontuse** [comment]
adb logs

04-19 19:49:27.679 19416 19467 W bt_btif : bta_dm_pm_cback: new conn_srvc id:26, app_id:1 count:1
04-19 19:49:27.684  2945  3632 D BluetoothService: create ConnectedThread
04-19 19:49:27.686 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:27.687  2945  3632 D BluetoothService: setState() STATE_CONNECTING -> STATE_CONNECTED
04-19 19:49:27.687  2945  3632 D BluetoothManager: on bluetoothServiceStatChange:3
04-19 19:49:27.687  2945  3632 D BluetoothManager: Promise Resolve.
04-19 19:49:27.688  2945  3632 I BluetoothService: Connected
04-19 19:49:27.689 19416 19467 W bt_rfcomm: port_rfc_closed: RFCOMM connection closed, index=19, state=2 reason=Closed[19], UUID=1101, bd_addr=00:0c:bf:2e:2a:e7, is_server=0
04-19 19:49:27.690 19416 19467 W bt_l2cap: L2CA_SetDesireRole() new:x1, disallow_switch:0
04-19 19:49:27.690 19416 19471 E bt_btif_sock_rfcomm: find_rfc_slot_by_id unable to find RFCOMM slot id: 136
04-19 19:49:27.691  2945  3632 E BluetoothService: disconnected
04-19 19:49:27.691  2945  3632 E BluetoothService: java.io.IOException: bt socket closed, read return: -1
04-19 19:49:27.691  2945  3632 E BluetoothService: 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:524)
04-19 19:49:27.691  2945  3632 E BluetoothService: 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
04-19 19:49:27.691  2945  3632 E BluetoothService: 	at java.io.InputStream.read(InputStream.java:101)
04-19 19:49:27.691  2945  3632 E BluetoothService: 	at cn.jystudio.bluetooth.BluetoothService$ConnectedThread.run(BluetoothService.java:292)
04-19 19:49:27.691  2945  3632 D BluetoothService: setState() STATE_CONNECTED -> STATE_NONE
04-19 19:49:27.691  2945  3632 D BluetoothManager: on bluetoothServiceStatChange:0
04-19 19:49:27.691  2945  3632 D BluetoothManager: on bluetoothServiceStatChange:8
04-19 19:49:27.692  2945  3632 I BluetoothService: ConnectedThread End
04-19 19:49:27.695 19416 19467 W bt_l2cap: L2CA_DisconnectReq()  CID: 0x004d
04-19 19:49:27.702 19416 19467 W bt_l2cap: L2CAP - LCID: 0x004d  st: W4_L2CAP_DISC_RSP  evt: PEER_DISCONNECT_REQ
04-19 19:49:27.749   728 19465 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
04-19 19:49:27.760 25675 25680 I zygote64: Compiler allocated 8MB to compile com.google.android.apps.gsa.search.core.state.d.ae com.google.android.apps.gsa.binaries.velvet.app.rm.cw()
04-19 19:49:27.865   728 19465 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
04-19 19:49:27.865   728 19465 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
04-19 19:49:27.870 19416 19467 I bt_btm_sec: btm_sec_disconnected clearing pending flag handle:21 reason:22
04-19 19:49:27.870 19416 19467 W bt_l2cap: L2CA_SetDesireRole() new:x1, disallow_switch:0
04-19 19:49:27.877 19416 19416 D BluetoothMapService: onReceive
04-19 19:49:27.877 19416 19416 D BluetoothMapService: onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
04-19 19:49:27.877 19416 19416 E BluetoothMapService: Unexpected error!
04-19 19:49:27.877 19416 19416 D BluetoothPbapService: action: android.bluetooth.device.action.ACL_DISCONNECTED
04-19 19:49:27.877 19416 19416 D BluetoothPbapService: state: -2147483648
04-19 19:49:27.881 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:27.909 19416 19455 I chatty  : uid=1002(bluetooth) Binder:19416_3 identical 5 lines
04-19 19:49:27.911 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:27.912   728 19465 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
04-19 19:49:28.651  1984  2964 W System.err: java.io.FileNotFoundException: /acct/uid_10020/pid_3342/cgroup.procs (No such file or directory)
04-19 19:49:28.652  1984  2964 W System.err: 	at java.io.FileInputStream.open0(Native Method)
04-19 19:49:28.652  1984  2964 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-19 19:49:28.652  1984  2964 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-19 19:49:28.652  1984  2964 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.miui.server.PerfShielderService.setForkedProcessGroup(PerfShielderService.java:198)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ExtraActivityManagerService.setForkedProcessGroup(ExtraActivityManagerService.java:1235)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerServiceInjector.setForkedProcessGroup(ActivityManagerServiceInjector.java:972)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:22565)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:23171)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:300)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1381)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:852)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.finishReceiver(ActivityManagerService.java:20391)
04-19 19:49:28.652  1984  2964 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:283)
04-19 19:49:28.652  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2997)
04-19 19:49:28.653  1984  2964 W System.err: 	at android.os.Binder.execTransact(Binder.java:700)
04-19 19:49:28.654  1984  2964 D CompatibilityInfo: mCompatibilityFlags - 0
04-19 19:49:28.654  1984  2964 D CompatibilityInfo: applicationDensity - 440
04-19 19:49:28.654  1984  2964 D CompatibilityInfo: applicationScale - 1.0
04-19 19:49:28.676  1984  2964 W System.err: java.io.FileNotFoundException: /acct/uid_10020/pid_3342/cgroup.procs (No such file or directory)
04-19 19:49:28.676  1984  2964 W System.err: 	at java.io.FileInputStream.open0(Native Method)
04-19 19:49:28.676  1984  2964 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-19 19:49:28.676  1984  2964 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-19 19:49:28.677  1984  2964 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.miui.server.PerfShielderService.setForkedProcessGroup(PerfShielderService.java:198)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ExtraActivityManagerService.setForkedProcessGroup(ExtraActivityManagerService.java:1235)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerServiceInjector.setForkedProcessGroup(ActivityManagerServiceInjector.java:972)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:22565)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:22948)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:23033)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2936)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2884)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:18863)
04-19 19:49:28.677  1984  2964 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:952)
04-19 19:49:28.677  1984  2964 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2997)
04-19 19:49:28.677  1984  2964 W System.err: 	at android.os.Binder.execTransact(Binder.java:700)
04-19 19:49:28.692  1984  2436 W System.err: java.io.FileNotFoundException: /acct/uid_10020/pid_3342/cgroup.procs (No such file or directory)
04-19 19:49:28.692  1984  2436 W System.err: 	at java.io.FileInputStream.open0(Native Method)
04-19 19:49:28.692  1984  2436 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-19 19:49:28.692  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-19 19:49:28.692  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.miui.server.PerfShielderService.setForkedProcessGroup(PerfShielderService.java:198)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.ExtraActivityManagerService.setForkedProcessGroup(ExtraActivityManagerService.java:1235)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerServiceInjector.setForkedProcessGroup(ActivityManagerServiceInjector.java:972)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:22565)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:23171)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:300)
04-19 19:49:28.692  1984  2436 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1381)
04-19 19:49:28.693  1984  2436 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:852)
04-19 19:49:28.693  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.finishReceiver(ActivityManagerService.java:20391)
04-19 19:49:28.693  1984  2436 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:283)
04-19 19:49:28.693  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2997)
04-19 19:49:28.693  1984  2436 W System.err: 	at android.os.Binder.execTransact(Binder.java:700)
04-19 19:49:28.693  1984  2436 D CompatibilityInfo: mCompatibilityFlags - 0
04-19 19:49:28.694  1984  2436 D CompatibilityInfo: applicationDensity - 440
04-19 19:49:28.694  1984  2436 D CompatibilityInfo: applicationScale - 1.0
04-19 19:49:28.702   728 19470 I vendor.qti.bluetooth@1.0-ibs_handler: DeviceSleep: TX Awake, Sending SLEEP_IND
04-19 19:49:28.702   728 19470 I vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK OFF
04-19 19:49:28.706 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:28.707 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:28.709 19416 19473 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:28.711 19416 19473 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:28.713 25675 25697 I DeviceDetector: UUID = 00001101-0000-1000-8000-00805f9b34fb
04-19 19:49:28.714 25675 25697 I DeviceDetector: UUID = 00000000-0000-1000-8000-00805f9b34fb
04-19 19:49:28.714 25675 25697 I DeviceDetector: UUID = 00000000-0000-1000-8000-00805f9b34fb
04-19 19:49:28.714 25675 25697 I DeviceDetector: UUID = ffcacade-afde-cade-defa-cade00000000
04-19 19:49:28.796   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:28.853   728 19461 E vendor.qti.bluetooth@1.0-wake_lock: Release wakelock is released 
04-19 19:49:29.587 19416 19455 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@f5786b3
04-19 19:49:31.800   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:34.801   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:35.703  1984  2436 W System.err: java.io.FileNotFoundException: /acct/uid_10020/pid_3342/cgroup.procs (No such file or directory)
04-19 19:49:35.704  1984  2436 W System.err: 	at java.io.FileInputStream.open0(Native Method)
04-19 19:49:35.704  1984  2436 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-19 19:49:35.704  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-19 19:49:35.704  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-19 19:49:35.704  1984  2436 W System.err: 	at com.miui.server.PerfShielderService.setForkedProcessGroup(PerfShielderService.java:198)
04-19 19:49:35.704  1984  2436 W System.err: 	at com.android.server.am.ExtraActivityManagerService.setForkedProcessGroup(ExtraActivityManagerService.java:1235)
04-19 19:49:35.704  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerServiceInjector.setForkedProcessGroup(ActivityManagerServiceInjector.java:972)
04-19 19:49:35.704  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:22565)
04-19 19:49:35.704  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:22948)
04-19 19:49:35.705  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:23033)
04-19 19:49:35.705  1984  2436 W System.err: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2936)
04-19 19:49:35.705  1984  2436 W System.err: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2884)
04-19 19:49:35.705  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:18863)
04-19 19:49:35.705  1984  2436 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:952)
04-19 19:49:35.705  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2997)
04-19 19:49:35.705  1984  2436 W System.err: 	at android.os.Binder.execTransact(Binder.java:700)
04-19 19:49:37.169  3180  3180 I BatteryInfoReceiver: ACTION_BATTERY_CHANGED
04-19 19:49:37.171  2205  2205 D BatteryController: action=android.intent.action.BATTERY_CHANGED; mCharging=true
04-19 19:49:37.174 19416 19476 D HeadsetStateMachine: Disconnected process message: 10, size: 0
04-19 19:49:37.174 19416 19476 D HeadsetStateMachine: Enter processIntentBatteryChanged()
04-19 19:49:37.175 19416 19476 D HeadsetStateMachine: Exit processIntentBatteryChanged()
04-19 19:49:37.175 19416 19476 D HeadsetStateMachine: Exit Disconnected processMessage() 
04-19 19:49:37.702 25675 32654 W NamedFutures: Timeout future task has been cancelled: 9000 milliseconds
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: Task COMMON_BROADCAST_MESSAGE_RECEIVED failed or timed out. Client 112921399852551083 disconnecting from SearchService!
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: java.util.concurrent.CancellationException: Task was cancelled.
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.common.r.a.c.b(SourceFile:103)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.common.r.a.c.get(SourceFile:81)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.common.r.a.dc.a(SourceFile:1)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.common.r.a.bg.a(SourceFile:33)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.common.r.a.bi.run(SourceFile:4)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.google.android.apps.gsa.shared.util.c.b.be.run(SourceFile:2)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at android.os.Handler.handleCallback(Handler.java:790)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at android.os.Looper.loop(Looper.java:164)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at android.app.ActivityThread.main(ActivityThread.java:6600)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at java.lang.reflect.Method.invoke(Native Method)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
04-19 19:49:37.703 25675 25675 E SearchServiceStarter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
04-19 19:49:37.717  1984  2436 W System.err: java.io.FileNotFoundException: /acct/uid_10020/pid_3342/cgroup.procs (No such file or directory)
04-19 19:49:37.717  1984  2436 W System.err: 	at java.io.FileInputStream.open0(Native Method)
04-19 19:49:37.717  1984  2436 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:200)
04-19 19:49:37.717  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
04-19 19:49:37.718  1984  2436 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.miui.server.PerfShielderService.setForkedProcessGroup(PerfShielderService.java:198)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ExtraActivityManagerService.setForkedProcessGroup(ExtraActivityManagerService.java:1235)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerServiceInjector.setForkedProcessGroup(ActivityManagerServiceInjector.java:972)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:22565)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:23171)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:946)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:852)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.finishReceiver(ActivityManagerService.java:20391)
04-19 19:49:37.718  1984  2436 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:283)
04-19 19:49:37.718  1984  2436 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2997)
04-19 19:49:37.718  1984  2436 W System.err: 	at android.os.Binder.execTransact(Binder.java:700)
04-19 19:49:37.805   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:38.044  2205  2205 D BatteryController: action=android.intent.action.BATTERY_CHANGED; mCharging=true
04-19 19:49:38.048  3180  3180 I BatteryInfoReceiver: ACTION_BATTERY_CHANGED
04-19 19:49:38.049 19416 19476 D HeadsetStateMachine: Disconnected process message: 10, size: 0
04-19 19:49:38.049 19416 19476 D HeadsetStateMachine: Enter processIntentBatteryChanged()
04-19 19:49:38.049 19416 19476 D HeadsetStateMachine: Exit processIntentBatteryChanged()
04-19 19:49:38.049 19416 19476 D HeadsetStateMachine: Exit Disconnected processMessage() 
04-19 19:49:38.441   749  2359 V LocSvc_HIDL_IzatProvider: [onLocationChanged][71] [HS] =>>>> [HC]
04-19 19:49:38.442  1984 29469 V LocSvc_HIDL_IzatProvider_jni: [onLocationChanged][136] [HC] <<= [HS]
04-19 19:49:38.444  1984  2035 D LocationManagerService: This location is marked as ready for broadcast
04-19 19:49:38.445  1984  2035 D LocationManagerService: incoming location: Location[network 56,826580,60,616133 hAcc=10106 et=+10d5h28m7s841ms alt=317.8999938964844 vel=0.0 bear=1.515625 vAcc=??? sAcc=??? bAcc=??? {Bundle[{networkLocationType=cell, noGPSLocation=Location[network 56,826580,60,616133 hAcc=10106 et=+10d5h28m7s841ms alt=317.8999938964844 vel=0.0 bear=1.515625 vAcc=??? sAcc=??? bAcc=??? {Bundle[{networkLocationType=cell}]}], com.qualcomm.location.nlp:ready=true}]}]
04-19 19:49:38.446  1984  2035 D LocationManagerService: incoming location: Location[network 56,826580,60,616133 hAcc=10106 et=+10d5h28m7s841ms alt=317.8999938964844 vel=0.0 bear=1.515625 vAcc=??? sAcc=??? bAcc=??? {Bundle[{networkLocationType=cell, noGPSLocation=Location[network 56,826580,60,616133 hAcc=10106 et=+10d5h28m7s841ms alt=317.8999938964844 vel=0.0 bear=1.515625 vAcc=??? sAcc=??? bAcc=??? {Bundle[{networkLocationType=cell}]}], com.qualcomm.location.nlp:ready=true}]}]
04-19 19:49:40.807   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:43.811   779   793 I chatty  : uid=0(root) /vendor/bin/mmid identical 1 line
04-19 19:49:46.814   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:47.726 25675 25697 I WorkerManager: dispose()
04-19 19:49:49.818   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:49:58.831   779   793 I chatty  : uid=0(root) /vendor/bin/mmid identical 3 lines
04-19 19:50:01.835   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:50:04.379  1984  2036 D CompatibilityInfo: mCompatibilityFlags - 0
04-19 19:50:04.379  1984  2036 D CompatibilityInfo: applicationDensity - 440
04-19 19:50:04.379  1984  2036 D CompatibilityInfo: applicationScale - 1.0
04-19 19:50:04.394  1984  2964 D CompatibilityInfo: mCompatibilityFlags - 0
04-19 19:50:04.395  1984  2964 D CompatibilityInfo: applicationDensity - 440
04-19 19:50:04.395  1984  2964 D CompatibilityInfo: applicationScale - 1.0
04-19 19:50:04.837   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:50:34.875   779   793 I chatty  : uid=0(root) /vendor/bin/mmid identical 10 lines
04-19 19:50:37.879   779   793 I mmid    : select timeout: wait for receiving msg
04-19 19:50:38.052  1984  2048 I WifiService: requestActivityInfo uid=1000
04-19 19:50:38.052  1984  2048 I WifiService: reportActivityInfo uid=1000
04-19 19:50:38.052  1984  2048 I WifiService: getSupportedFeatures uid=1000

**Comment by dontuse** [comment]
i removed  this
            // try to connect with socket inner method firstly.
            // for(int i=1;i<=3;i++) {
            //     try {
            //         tmp = (BluetoothSocket) mmDevice.getClass().getMethod("createRfcommSocket", int.class).invoke(mmDevice, i);
            //     } catch (Exception e) {
            //     }
            //     if(tmp!=null){
            //         mmSocket = tmp;
            //         break;
            //     }
            // }

and connect with this mmDevice.createRfcommSocketToServiceRecord(MY_UUID); work fine !

**Comment by januslo** [comment]
will do further test about this part, thx a lot.

**Comment by fnaquira** [comment]
> 
> 
> i removed this
> // try to connect with socket inner method firstly.
> // for(int i=1;i<=3;i++) {
> // try {
> // tmp = (BluetoothSocket) mmDevice.getClass().getMethod("createRfcommSocket", int.class).invoke(mmDevice, i);
> // } catch (Exception e) {
> // }
> // if(tmp!=null){
> // mmSocket = tmp;
> // break;
> // }
> // }
> 
> and connect with this mmDevice.createRfcommSocketToServiceRecord(MY_UUID); work fine !

Where did you do this?
